# This is a basic workflow to help you get started with Actions

name: Build

# Cache thing is from YoshiCrafter29, thanks!!!

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildLinux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
      # Runs a set of commands using the runners shell
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: cache-build-linux
          path: |
            .haxelib/
            export/release/linux/haxe/
            export/release/linux/obj/
          restore-keys: |
            cache-build-linux
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup --always
          haxelib run lime setup flixel --always
          haxelib git hscript-lore https://github.com/sayofthelor/hscript-lore legacy
      - name: Compile
        run: haxelib run lime build Project.xml hl
      - name: Fix Mac Run
        run: chmod +x export/release/mac/bin/msmp
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: msmp-linux
          path: 'export/hl/bin'
  buildWindows:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
      # Runs a set of commands using the runners shell
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: cache-build-windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          restore-keys: |
            cache-build-windows
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup --always
          haxelib run lime setup flixel --always
          haxelib git hscript-lore https://github.com/sayofthelor/hscript-lore legacy
      - name: Compile
        run: haxelib run lime build hl
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: msmp-windows
          path: export/hl/bin
  buildMac:
    runs-on: macos-13

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6
      # Runs a set of commands using the runners shell
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: cache-build-mac
          path: |
            .haxelib/
            export/release/mac/haxe/
            export/release/mac/obj/
          restore-keys: |
            cache-build-mac
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup -y
          haxelib run lime setup flixel -y
          haxelib git hscript-lore https://github.com/sayofthelor/hscript-lore legacy

      - name: Compile
        run: haxelib run lime build hl
      - name: Fix Mac Run
        run: chmod -R +x export/hl/bin/msmp.app/Contents/MacOS/
      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macBuild
          path: export/hl/bin
  